name: compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile project
        uses: miyako/4d-class-build-application@v1
        run: |
          userParams="" 
          curl -fsSL https://.../run.sh | bash -s ${{ secrets.SERVER_URL }} "$userParams"
